=== Eswar508/api_testing_frameworks/mock_api_testing/MockApiTesting_response/mock_api/jsons/json_schemas/schema_put.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type":"object",
    "properties": 
    {
        "name":{"type":"string"},
        "age":{"type":"integer"},
        "email":{"type":"string","format": "email"},
        "result":{"type":"string","enum": ["passed","failed"]}
    }
}

=== Eswar508/api_testing_frameworks/mock_api_testing/MockApiTesting_response/mock_api/jsons/data_source/post.json
[
    {
        "name": "usern",
        "age": 34,
        "email": "usern@gmail.com",
        "result": "failed"
    },
    {
        "name": "userm",
        "age": 35,
        "email": "userm@gmail.com",
        "result": "passed"
    },
    {
        "name": "usero",
        "age": 36,
        "email": "usero@gmail.com",
        "result": "passed"
    }
]
